### GET /
GET http://localhost:5000

### Register a new user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "sayed@hotmail.com",
    "password": "sayed@hotmail.com"
}

### Login user to get JWT token
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "sayed@hotmail.com",
    "password": "sayed@hotmail.com"
}

### Fetch all todos GET /TODOS (protected)
GET http://localhost:5000/todos
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU5NTczMjYyLCJleHAiOjE3NTk2NTk2NjJ9.82mPzcYN5C1FD9PcoXfLZWi2w8PvUHgUXBOgff40gpI

### Create a new todo POST /TODOS (protected)
POST http://localhost:5000/todos
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU5NTczMjYyLCJleHAiOjE3NTk2NTk2NjJ9.82mPzcYN5C1FD9PcoXfLZWi2w8PvUHgUXBOgff40gpI
Content-Type: application/json

{
    "task": "Finish coding the project"
}


### Update a todo PUT /TODOS/:id (protected)
PUT http://localhost:5000/todos/2
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU5NTczMjYyLCJleHAiOjE3NTk2NTk2NjJ9.82mPzcYN5C1FD9PcoXfLZWi2w8PvUHgUXBOgff40gpI
Content-Type: application/json

{
    "completed": 1
}